async (page) => {
 const assert=(ok,message)=>{if(!ok)throw new Error(message);};
 await page.goto('http://127.0.0.1:5173/profile');
 await page.getByLabel('Light in your space').selectOption('Evening');
 await page.getByRole('checkbox',{name:/Less movement/}).check();
 await page.getByRole('link',{name:'Today',exact:true}).click();
 assert(await page.locator('.steam i').first().evaluate(el=>getComputedStyle(el).animationName)==='none','Reduced motion preference');
 await page.addScriptTag({path:'node_modules/axe-core/axe.min.js'});
 const result=await page.evaluate(async()=>{const r=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return r.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)}));});
 assert(result.length===0,JSON.stringify(result));
 await page.getByRole('button',{name:'Finish the homepage concept',exact:true}).click();
 const dialog=page.getByRole('dialog',{name:'A little finish'});
 await dialog.waitFor();
 for(let i=0;i<8;i++){await page.keyboard.press('Tab');assert(await dialog.evaluate(el=>el.contains(document.activeElement)),'Focus escaped the modal');}
 await page.keyboard.press('Escape');
 assert(await dialog.count()===0,'Escape did not close dialog');
 await page.goto('http://127.0.0.1:5173/today');
 await page.keyboard.press('Tab');
 assert(await page.getByRole('link',{name:'Skip to content'}).evaluate(el=>el===document.activeElement),'Skip link is not first keyboard target');
 await page.keyboard.press('Enter');
 assert(await page.locator('main').evaluate(el=>el===document.activeElement),'Skip link did not focus main');
 await page.getByRole('link',{name:'Profile',exact:true}).click();
 const next=await page.evaluate(()=>{const d=new Date(Date.now()+60000);return String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0');});
 await page.getByLabel('A gentle daily reminder').fill(next);
 await page.clock.fastForward(61000);
 await page.getByRole('status').filter({hasText:'Anything worth finishing today?'}).waitFor();
 await page.getByRole('button',{name:'Turn reminder off'}).click();
 await page.getByRole('button',{name:'Dismiss message'}).click();
 await page.getByLabel('Light in your space').selectOption('Morning');
 await page.getByRole('checkbox',{name:/Less movement/}).uncheck();
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.getByRole('link',{name:'Today',exact:true}).click();
 assert(await page.locator('.steam i').first().evaluate(el=>getComputedStyle(el).animationName)==='none','System reduced motion');
 await page.emulateMedia({reducedMotion:'no-preference'});
 await page.getByRole('link',{name:'Focus',exact:true}).click();
 await page.getByRole('button',{name:'Custom',exact:true}).click();
 await page.getByRole('spinbutton').fill('1');
 await page.getByRole('button',{name:'Begin a quiet moment'}).click();
 await page.clock.fastForward(61000);
 await page.getByRole('heading',{name:'That was enough for now.'}).waitFor();
 await page.reload();
 await page.getByRole('heading',{name:'That was enough for now.'}).waitFor();
 await page.getByRole('button',{name:'Back to your day'}).click();
 await page.getByRole('link',{name:'Journal',exact:true}).click();
 await page.getByRole('link').filter({hasText:'A small thought worth keeping.'}).click();
 await page.getByRole('button',{name:'Delete entry',exact:true}).click();
 await page.getByRole('dialog').getByRole('button',{name:'Delete entry',exact:true}).click();
 assert(await page.getByRole('link').filter({hasText:'A small thought worth keeping.'}).count()===0,'Entry was not deleted');
 return {eveningAccessibility:result,keyboardFocusAndEscape:true,skipLink:true,settingsAndSystemReducedMotion:true,inAppReminder:true,completionReload:true,journalDeletion:true};
}
